version: '3'

services:
  userpanel:
    container_name: '${CONSOLE_PROD_CONTAINER_NAME}'
    build:
      context: .
      dockerfile: docker/production/Dockerfile.prod

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - 'userpanel-data:/userpanel'
      # - /app/node_modules

    restart: '${PROD_RESTART_MODE}'
    ports:
      - '${PROD_PORT}:4173'
    networks:
      - consolenetwork

networks:
  consolenetwork:
    driver: bridge

# Volumes
volumes:
  userpanel-data:
    driver: local
